function Tlong = makeTrialMetricsLongTable(trialNumber, idxValue, alphaSVD, alphaBlue, resultsSummary)
% Converte resultsSummary in formato aggregabile.

    % Estrae in formato stringa i nomi dei modelli valutati
    models = string(resultsSummary.Model);

    % Costruisce una sotto-tabella dedicata esclusivamente al metodo SVD
    Tsvd = table( ...
        repmat(trialNumber, height(resultsSummary), 1), ...
        repmat(idxValue, height(resultsSummary), 1), ...
        repmat(alphaSVD, height(resultsSummary), 1), ...
        repmat("SVD", height(resultsSummary), 1), ...
        models, ...
        resultsSummary.SVD_Accuracy, ...
        resultsSummary.SVD_Precision, ...
        resultsSummary.SVD_Recall, ...
        resultsSummary.SVD_F1, ...
        resultsSummary.SVD_AUC, ...
        'VariableNames', {'Trial','idx','alpha','Technique','Model', ...
                          'Accuracy','Precision','Recall','F1','AUC'} ...
    );

    % Costruisce una sotto-tabella dedicata esclusivamente al metodo Blu
    Tblu = table( ...
        repmat(trialNumber, height(resultsSummary), 1), ...
        repmat(idxValue, height(resultsSummary), 1), ...
        repmat(alphaBlue, height(resultsSummary), 1), ...
        repmat("Blu", height(resultsSummary), 1), ...
        models, ...
        resultsSummary.Blu_Accuracy, ...
        resultsSummary.Blu_Precision, ...
        resultsSummary.Blu_Recall, ...
        resultsSummary.Blu_F1, ...
        resultsSummary.Blu_AUC, ...
        'VariableNames', {'Trial','idx','alpha','Technique','Model', ...
                          'Accuracy','Precision','Recall','F1','AUC'} ...
    );

    % Concatena verticalmente le due sotto-tabelle (SVD e Blu)
    Tlong = [Tsvd; Tblu];
end
